This \* is < a & <code> block &lt;:
And here's an <johnw@gnu.org> email
and here's <http://johnwiegley.com>.

1\. How de doo.

    Hello there
        I'm & piece of code


This is a `code` word.
This is a ``coded ` message``.
