This is a *serious* ``allegation`` -- ``made'' by who?
So 'she' said, "I know who",
but I'm [The "real" Google](/google) hardly likely to believe that...

"*Blockquotes*" are indicated using email-style '`>`' angle brackets.
