here's an <johnw@gnu.org> email

here's a <http://johnwiegley.com> url

here's a [Google](http://google.com "Google!") link

here's another [Google](http://google.com) link

here's another [Google][1] link

here's another [Google] [2] link

  [1]: http://google.com
  [2]: http://google2.com "A happy title"

And a last paragraph.
